### ISSUE TITLE
Potential Infinite Loop and Redundant Check in City Query Method

### ISSUE THREAD

**Issue by Luphone** [PhonePyaePhyoee/DevOpGp6#49]
Issue:
In the getAllCitiesOrderedByPopulation method (and similar methods), there is a potential inefficiency due to incorrect loop structure. The current implementation of the while (rs.next()) loop processes ResultSet rows, but unnecessary checks or looping structure issues can arise, particularly if the initial rs.next() is placed outside the loop, causing missed or duplicated entries.

Root Cause:
The bug occurs because the first rs.next() is sometimes placed before the loop body, causing an off-by-one error, which either skips the first row of the ResultSet or leads to redundant checks and empty results.

Solution:
The correct approach is to directly use the while (rs.next()) loop without the extra if (rs.next()) check before it.

**Comment by ShaneBhoneAung** [comment]
<img width="340" alt="Screenshot 2024-10-19 at 10 32 12 am" src="https://github.com/user-attachments/assets/c194bca9-5e7c-4d96-8b1b-c43069d1db4d">
