### ISSUE TITLE
Improved Messaging for Zero Population Handling in City Population Display

### ISSUE THREAD

**Issue by WunaPhyoPaing** [PhonePyaePhyoee/DevOpGp6#51]
Potential Bug: In the displayCityPopulation method, if the populations list is empty or contains a population value of 0, the display output may lead to confusion or provide misleading information.

How It Could Happen:
Empty List: If there is no data for the specified city (i.e., the getPopulation method returns an empty list), the output will indicate that no population data was found, which is correct.
Zero Population: If a city exists in the database but has a population of 0, the message will indicate the population as Population: 0, which might not provide meaningful context to the user.
How to Fix It:
Improved Message for Zero Population: Instead of displaying Population: 0, provide a more informative message, such as "The population for this city is currently recorded as 0."
Example Fix for the displayCityPopulation Method:

java code sample
public void displayCityPopulation(List<Population> populations, String cityName) {
    if (populations == null || populations.isEmpty()) {
        System.out.println("No population data found for the city: " + cityName);
        return;
    }

    // Get the population data for the city (assuming it's the first in the list)
    Population cityPopulation = populations.get(0);

    // Header for the city population report
    System.out.println("Population of " + cityName + ":");

    // Display the total population in the desired format
    if (cityPopulation.getTotalPopulation() == 0) {
        System.out.println("The population for this city is currently recorded as 0.");
    } else {
        System.out.println("Population: " + String.format("%,d", cityPopulation.getTotalPopulation()));
    }
}
Explanation:
Clear Messaging: Providing clear feedback for different cases (empty list and zero population) improves user understanding and helps prevent misinterpretation of the data.
Simplicity: The fix is straightforward and easy to implement, requiring minimal changes to the existing logic.

**Comment by ShaneBhoneAung** [comment]
![Uploading Screenshot 2024-10-18 at 9.12.11 am.png…]()
